
name: Update WakaTime readme

# anmol098/waka-readme-stats@master
# athul/waka-readme@master
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
